#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=acclaim
MANUFACTURER=bn
OUTDIR=vendor/$MANUFACTURER/$DEVICE

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/setup-makefiles.sh

PRODUCT_COPY_FILES := \\
    $OUTDIR/proprietary/audio/libaudio.so:obj/lib/libaudio.so \\
    $OUTDIR/proprietary/audio/libaudiopolicy.so:obj/lib/libaudiopolicy.so

\$(call inherit-product, vendor/__MANUFACTURER__/__DEVICE__/device-vendor-blobs.mk)
EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/BoardConfigVendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/setup-makefiles.sh
EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# sound libs

PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/libaudio.so:/system/lib/libaudio.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/liba2dp.so:/system/lib/liba2dp.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/hw/alsa.omap4.so:/system/lib/hw/alsa.omap4.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/libasound.so:/system/lib/libasound.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/libaudiopolicy.so:/system/lib/libaudiopolicy.so


# sound conf
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/etc/asound.conf:/system/etc/asound.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/alsa.conf:/system/usr/share/alsa/alsa.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/cards/aliases.conf:/system/user/share/cards/aliases.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/center_lfe.conf:/system/user/share/pcm/center_lfe.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/default.conf:/system/user/share/pcm/center_lfe.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/dmix.conf:/system/user/share/pcm/dmix.com \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/dpl.conf:/system/user/share/pcm/dpl.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/dsnoop.conf:/system/user/share/pcm/dsnoop.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/front.conf:/system/user/share/pcm/front.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/iec958.conf:/system/user/share/pcm/iec958.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/modem.conf:/system/user/share/pcm/modem.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/rear.conf:/system/user/share/pcm/rear.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/side.conf:/system/user/share/pcm/side.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/surround40.conf:/system/user/share/pcm/surround40.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/surround41.conf:/system/user/share/pcm/surround41.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/surround50.conf:/system/user/share/pcm/surround50.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/surround51.conf:/system/user/share/pcm/surround51.conf \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/audio/conf/pcm/surround71.conf:/system/user/share/pcm/surround71.conf

# gfx

PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/egl/libEGL_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/egl/libGLESv1_CM_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/egl/libGLESv2_POWERVR_SGX540_120.so:/system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/hw/gralloc.omap4.so:/system/vendor/lib/hw/gralloc.omap4.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/libIMGegl.so:/system/vendor/lib/libIMGegl.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/libPVRScopeServices.so:/system/vendor/lib/libPVRScopeServices.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/libglslcompiler.so:/system/vendor/lib/libglslcompiler.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/libpvr2d.so:/system/vendor/lib/libpvr2d.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/libpvrANDROID_WSEGL.so:/system/vendor/lib/libpvrANDROID_WSEGL.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/libsrv_init.so:/system/vendor/lib/libsrv_init.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/libsrv_um.so:/system/vendor/lib/libsrv_um.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/libusc.so:/system/vendor/lib/libusc.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gfx/bin/pvrsrvinit:/system/bin/pvrsrvinit


EOF
