#!/usr/bin/env python
#
# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os, sys

LOCAL_DIR = os.path.abspath \
    (os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
RELEASETOOLS_DIR = os.path.abspath \
    (os.path.join(LOCAL_DIR, '../../../build/tools/releasetools'))

def GetBootableImage(name, prebuilt_name, unpack_dir, tree_subdir,
                     info_dict = None):
    new_name =  os.path.abspath \
        (os.path.join(LOCAL_DIR, 
                      '../../../out/target/product/acclaim/%s') % name)

    print "For acclaim we keep %s as %s" % (name, new_name)
    return File.FromLocalFile(name, new_name)

def load_module_from_file(module_name, filename):
    import imp
    f = open(filename, 'r')
    module = imp.load_module(module_name, f, filename, ('', 'U', 1))
    f.close()
    return module

# Add releasetools directory to python path
sys.path.append(RELEASETOOLS_DIR)

import common
common.GetBootableImage = GetBootableImage

from common import *

# Import the existing file so we just have to rewrite the modules we need.
# This is a nasty hack as the filename doesn't end in .py, but it works
# Thx to nemith.
filename = os.path.join(RELEASETOOLS_DIR, "ota_from_target_files")
ota_from_target_files = load_module_from_file('ota_from_target_files', filename)

from ota_from_target_files import *

if __name__ == '__main__':
  try:
    common.CloseInheritedPipes()
    ota_from_target_files.main(sys.argv[1:])
  except common.ExternalError, e:
    print
    print "   ERROR: %s" % (e,)
    print
    sys.exit(1)
